name: Build API Docs

on:
  workflow_call:
    inputs:
      project:
        description: "Github repo to build docs for"
        required: true
        default: "JarrodCTaylor/data.fressian"
        type: string

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'

    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@11.0
      with:
          cli: 'latest'

    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-

    - name: Clone repo to doc
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.project }}
        path: repo
        fetch-depth: 0

    - name: Clone contrib api repo
      uses: actions/checkout@v3
      with:
        repository: JarrodCTaylor/contrib-api-doc
        path: repo/contrib-api-doc
        fetch-depth: 0

    - name: Clone build repo
      uses: actions/checkout@v3
      with:
        repository: JarrodCTaylor/build.ci
        path: repo/build.ci
        fetch-depth: 0

    - name: Call clojure-api-doc build.sh
      run:  |
        bash ./repo/build.ci/build.sh ${{ inputs.project }}

    - name: Commit
      run: |
        git config --global user.name clojure-build
        git config --global user.email "clojure-build@users.noreply.github.com"
        git config --global push.default simple
        ls
        echo "Changing Dirs"
        cd repo #/repo-docs
        ls
        echo "Tree"
        tree
        git add -u -v
        git commit -m "Autodoc commit"
        # git push origin gh-pages
